# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Prod

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: dart pub get

      - name: Analyze project source
        run: dart analyze

      - name: build docker image
        run: docker build . --file Dockerfile --tag server-prod:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ndhrbt1
          password: indah1234

      - name: docker tag
        run: docker tag server-prod:latest ndhrbt1/app-prod:latest

      - name: docker push
        run: docker push ndhrbt1/app-prod:latest
